development:
  sessions:
    default:
      database: clock_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: clock_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: clock_production
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true
    preload_models:
      - User
      - Note
    use_activesupport_time_zone: true
