#!/bin/bash

mkdir -p tmp/pids log

unicorn -c script/unicorn.rb -E production -p 3000 -D

if [ -f tmp/pids/unicorn.pid ];
then
  echo "Exit status 0"
  exit 0
else
  echo "Exit status 1"
  exit 1
fi
